In [2]:
'''
𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙 = 𝐺𝑒𝑛𝑃𝑜𝑏()//Generar poblaciones aleatorias
𝑚𝑎𝑥𝐼𝑡𝑒𝑟𝑎𝑐𝑖𝑜𝑛𝑒𝑠 = 100
𝑐𝑜𝑛𝑡𝑎𝑑𝑜𝑟 = 0
𝑓𝑖𝑡𝑛𝑒𝑠𝑠 = 𝑔𝑒𝑡𝐹𝑖𝑡𝑛𝑒𝑠𝑠(𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙)
𝑊ℎ𝑖𝑙𝑒(𝑐𝑜𝑛𝑡𝑎𝑑𝑜𝑟 < 𝑚𝑎𝑥𝐼𝑡𝑒𝑟𝑎𝑐𝑖𝑜𝑛𝑒𝑠){
𝑐𝑟𝑜𝑠𝑠 = 𝑐𝑟𝑜𝑠𝑠𝑜𝑣𝑒𝑟(𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙, 0. 7)
𝑚𝑢𝑡 = 𝑚𝑢𝑡𝑎𝑐𝑖ó𝑛(𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙, 0. 3)
𝑛𝑒𝑤𝑃𝑜𝑏 = 𝑐𝑟𝑜𝑠𝑠. 𝑎𝑝𝑝𝑒𝑛𝑑(𝑚𝑢𝑡)
𝑛𝑒𝑤𝐹𝑖𝑡𝑛𝑒𝑠𝑠 = 𝑔𝑒𝑡𝐹𝑖𝑡𝑛𝑒𝑠𝑠(𝑛𝑒𝑤𝑃𝑜𝑏)
𝑖𝑓(𝑛𝑒𝑤𝐹𝑖𝑡𝑛𝑒𝑠𝑠 > 𝑓𝑖𝑡𝑛𝑒𝑠𝑠)
𝑓𝑖𝑡𝑛𝑒𝑠𝑠 = 𝑛𝑒𝑤𝐹𝑖𝑡𝑛𝑒𝑠𝑠
𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙 = 𝑔𝑒𝑡𝑃𝑜𝑏(𝑛𝑒𝑤𝑃𝑜𝑏, 𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙)//devuelve 50% de los
mejores, 25% aleatorio y 25% de los mejores de la población
anterior
𝑐𝑜𝑛𝑡𝑎𝑑𝑜𝑟 ++
}
𝑠𝑜𝑙𝑢𝑐𝑖ó𝑛 = 𝑔𝑒𝑡𝑀𝑒𝑗𝑜𝑟𝐶𝑟𝑜𝑚𝑜𝑠𝑜𝑚𝑎(𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙)
𝑟𝑒𝑡𝑢𝑟𝑛 𝑠𝑜𝑙𝑢𝑐𝑖ón

Conjuntos:

P: pueblos p={1, 2, 3, 4, 5, 6}
D: distancias entre antenas d={2.5, 5, 10} [Km]
Row: filas en la grilla r={1,...,9}
Col: columnas en la final c={1,...,13}

Parámetros:

Td: Tasa de bits en enlace a distancia d
C: Costo de antena
Dp: Demografía ciudad p. (Cantidad de habitantes)

Variables:

EP_r,c: {1, si existe pueblo en (r,c); 0, e.o.c.}
AA_r,c: {1, si el area en (r,c) es accesible; 0, e.o.c.}
UA_r,c: {1, si hay una antena ubicada en (r,c); 0, e.o.c.}
Tp: tasa de bits en pueblo p.

FO:

alpha*(1/sum(UA_r,c * C)) + (1-alpha)Tp*Dp

'''
import numpy as np

![image](grilla.png)

In [17]:
max_iteraciones = 100
contador = 0
costo_antenas = 100
bit_rates = [10, 1, 0.1]
best_poblation = np.zeros((9,13))
avalaible_areas = np.ones((9,13))
#print(avalaible_areas,
#avalaible_areas.shape)

inaccessible = np.array([0, 1, 2, 6, 12,
                13, 22, 25,
                26, 27, 28, 29 ,30, 35, 38,
               39, 40, 41, 42, 47, 49,
               52, 53, 54, 55, 56, 60, 61, 62, 64,
               65, 66, 67, 68, 69, 70, 73, 75,
               78, 79, 80, 81, 82, 83,
               91, 92, 93, 94, 95, 96, 97,
               104, 105, 106, 107, 108, 109, 110, 113])

def getAvalaibleAreas(inaccessible_vector):
    avalaible_areas = np.ones((9,13))
    for row in range(avalaible_areas.shape[0]):
        for col in range(avalaible_areas.shape[1]):
            if row*avalaible_areas.shape[1] + col in inaccessible_vector:
                avalaible_areas[row][col] = 0
    return avalaible_areas


print(getAvalaibleAreas(inaccessible))

[[0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1.]]


In [18]:
town_matrix = np.zeros((9, 13))

ISP = 116

town = np.array([
    14, 20, 21,
    46,
    76,
    111, ISP
])



for row in range(town_matrix.shape[0]):
    for col in range(town_matrix.shape[1]):
        if row*town_matrix.shape[1] + col in town:
            town_matrix[row][col] = 1
            

print(town_matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]


In [19]:
np.random.uniform(0, 1)

0.06959570809729987

In [20]:
def genPob(inaccessible_areas, towns, n=1):
    poblation_matrix = np.array([[]])
    for iter in range(n):
        antenna_matrix = np.zeros((9, 13))
        for row in range(antenna_matrix.shape[0]):
            for col in range(antenna_matrix.shape[1]):
                if ((row*antenna_matrix.shape[1] + col not in inaccessible_areas and np.random.uniform(0, 1) >= 0.5) or (row*antenna_matrix.shape[1] + col in towns)):
                    antenna_matrix[row][col] = 1
        #print(antenna_matrix)
        if poblation_matrix.size == 0:
            poblation_matrix = antenna_matrix
        else:
            poblation_matrix = np.append(poblation_matrix, antenna_matrix, axis=0)
    return poblation_matrix
    

In [38]:
poblation = genPob(inaccessible, town)
print(poblation)

[[0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1.]]


In [39]:
def getMovVector(pos, cols):
    mov = [                                            pos - 3*cols,
                   pos - 2*cols - 2, pos - 2*cols - 1, pos - 2*cols, pos - 2*cols + 1, pos - 2*cols + 2,
                       pos - cols - 2, pos - cols - 1, pos - cols, pos - cols + 1, pos - cols + 2,
                               pos - 3, pos - 2, pos - 1, pos, pos + 1, pos + 2, pos + 3,
                       pos + cols - 2, pos + cols - 1, pos + cols, pos + cols + 1, pos + cols + 2,
                   pos + 2*cols - 2, pos + 2*cols - 1, pos + 2*cols, pos + 2*cols + 1, pos + 2*cols + 2,
                                                       pos + 3*cols]
    dist = [          3,
                3, 2, 2, 2, 3,
                2, 1, 1, 1, 2,
             3, 2, 1, 0, 1, 2, 3,
                2, 1, 1, 1, 2,
                3, 2, 2, 2, 3,
                      3]
    return mov, dist

In [56]:
'''
block_sight_index = [ -,
                -, -, 0, -, -,
                -, 1, 2, 3, -,
             -, 4, 5, 6, 7, 8, -,
                -, 9, 10, 11, -,
                -, -, 12, -, -,
                      -]
                      
movs_index = [        0,
                1, 2, 3, 4, 5,
                6, 7, 8, 9, 10,
          11, 12, 13, 14, 15, 16, 17,
              18, 19, 20, 21, 22,
              23, 24, 25, 26, 27,
                      28]

'''

def getLOS(curr_pos, movs, inaccessible_vector):
    LOS = movs.copy()
    #print(movs)
    for (i,mov) in enumerate(movs):
        #print(i, mov)
        if mov in inaccessible_vector:
            if i == 3 and movs[0] in LOS:
                LOS.pop(LOS.index(movs[0]))
            elif i == 7:
                if movs[6] in LOS:
                    LOS.pop(LOS.index(movs[6]))
                if movs[1] in LOS:
                    LOS.pop(LOS.index(movs[1]))
                if movs[2] in LOS:
                    LOS.pop(LOS.index(movs[2]))
            elif i == 8 and movs[3] in LOS:
                LOS.pop(LOS.index(movs[3]))
            elif i == 9:
                if movs[4] in LOS:
                    LOS.pop(LOS.index(movs[4]))
                if movs[5] in LOS:
                    LOS.pop(LOS.index(movs[5]))
                if movs[10] in LOS:
                    LOS.pop(LOS.index(movs[10]))
            elif i == 12 and movs[11] in LOS:
                LOS.pop(LOS.index(movs[11]))
            elif i == 13:
                if movs[12] in LOS:
                    LOS.pop(LOS.index(movs[12]))
                if movs[11] in LOS:
                    LOS.pop(LOS.index(movs[11]))
            elif i == 15:
                if movs[16] in LOS:
                    LOS.pop(LOS.index(movs[16]))
                if movs[17] in LOS:
                    LOS.pop(LOS.index(movs[17]))
            elif i == 16 and movs[17] in LOS:
                LOS.pop(LOS.index(movs[17]))
            elif i == 19:
                if movs[18] in LOS:
                    LOS.pop(LOS.index(movs[18]))
                if movs[23] in LOS:
                    LOS.pop(LOS.index(movs[23]))
                if movs[24] in LOS:
                    LOS.pop(LOS.index(movs[24]))
            elif i == 20:
                if movs[25] in LOS:
                    LOS.pop(LOS.index(movs[25]))
                if movs[28] in LOS:
                    LOS.pop(LOS.index(movs[28]))
            elif i == 21:
                if movs[22] in LOS:
                    LOS.pop(LOS.index(movs[22]))
                if movs[26] in LOS:
                    LOS.pop(LOS.index(movs[26]))
                if movs[27] in LOS:
                    LOS.pop(LOS.index(movs[27]))
            elif i == 25 and movs[28] in LOS:
                LOS.pop(LOS.index(movs[28]))
    print("LOS: ", LOS)
    return LOS
                    
getLOS(38, getMovVector(38, 13)[0], inaccessible)
    
    

LOS:  [10, 11, 23, 24, 25, 26, 35, 36, 37, 38, 39, 49, 50, 51, 52, 62, 63, 64]


[10, 11, 23, 24, 25, 26, 35, 36, 37, 38, 39, 49, 50, 51, 52, 62, 63, 64]

In [69]:
def getShortRoute(poblation_matrix, towns):
    possible_route = False
    rows = poblation_matrix.shape[0]
    cols = poblation_matrix.shape[1]
    vision_sizes = [1, 2, 3]
    routes = []
    for town in towns:
        print(poblation_matrix)
        if town == ISP:
            continue
        town_route = [(town, 0)]
        curr_pos = town
        ignore = [0]
        while curr_pos != 116:
            movs, dist = getMovVector(curr_pos, cols)
            los = getLOS(curr_pos, movs, inaccessible)
            orientation_x = curr_pos % cols
            orientation_y = int(curr_pos/cols)
            
            isp_orientation_x = ISP % cols
            isp_orientation_y = int(ISP/cols)
            
            print(orientation_x, orientation_y, curr_pos)
            #break
            candidate = 0
            dist_pos = 0
            print("Movs: ", movs)
            cost = 100
            for i, mov in enumerate(movs):
                tmp_orientation_y = orientation_y
                tmp_orientation_x = mov % cols
                
                if mov < 0 or mov > 116:
                    continue
                    
                elif i == 0:
                    tmp_orientation_y = orientation_y - 3
                elif i >= 1 and i <= 5:
                    tmp_orientation_y = orientation_y - 2
                    if tmp_orientation_y != int(mov/cols):
                        continue
                elif i >= 6 and i <= 10:
                    tmp_orientation_y = orientation_y - 1
                    if tmp_orientation_y != int(mov/cols):
                        continue

                elif i >= 11 and i <= 17:
                    tmp_orientation_y = orientation_y
                    if tmp_orientation_y != int(mov/cols):
                        continue
                        
                elif i >= 18 and i <= 22:
                    tmp_orientation_y = orientation_y + 1
                    if tmp_orientation_y != int(mov/cols):
                        continue
                        
                elif i >= 23 and i <= 27:
                    tmp_orientation_y = orientation_y + 2
                    if tmp_orientation_y != int(mov/cols):
                        continue
                elif i == 28:
                    tmp_orientation_y = orientation_y + 3
                #print(poblation_matrix)
                print(tmp_orientation_y, tmp_orientation_x)
                print(f"Ignore list: {ignore}", "mov: ", mov, "index: ", i, (mov,dist[i]), f"Ruta ciudad: {town_route}")
                print(poblation_matrix[tmp_orientation_y], poblation_matrix[tmp_orientation_y][tmp_orientation_x], poblation_matrix[tmp_orientation_y][tmp_orientation_x] == 1)
                print(mov, los, mov in los)
                if poblation_matrix[tmp_orientation_y][tmp_orientation_x] == 1 and mov not in ignore and mov not in [rute for (rute, dist) in town_route] and mov in los:
                    dif_x = isp_orientation_x - tmp_orientation_x
                    dif_y = isp_orientation_y - tmp_orientation_y
                    print(f"Cost: {cost}, {dif_x + dif_y + dist[i]*1.2}")
                    print(cost > dif_x + dif_y + dist[i]*2)
                    if cost > dif_x + dif_y + dist[i]*2:
                        cost = dif_x + dif_y + dist[i]*2
                        dist_pos = i
                        print("Mov: ", mov)
                        candidate = mov
               
            print("Candidate: ", candidate)
            if candidate != 0:
                print(f"Ruta ciudad: {town_route}")
                town_route.append((candidate, dist[dist_pos]))
                curr_pos = candidate
            else:
                print(f"Ruta ciudad: {town_route}")
                if town_route[-1] != (town, 0):
                    print(town_route[-1])
                    ignore.append(town_route[-1][0])
                    town_route.pop()
                    curr_pos = town_route[-1][0]
                else:
                    break
                    
        
        print(town_route)
        routes.append(town_route)
        
    print(routes)
    
    return routes

In [70]:
routes = getShortRoute(poblation, town)

[[0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1.]]
LOS:  [-25, 0, 1, 2, 13, 14, 15, 16, 17, 26, 27, 28]
1 1 14
Movs:  [-25, -14, -13, -12, -11, -10, -1, 0, 1, 2, 3, 11, 12, 13, 14, 15, 16, 17, 25, 26, 27, 28, 29, 38, 39, 40, 41, 42, 53]
0 0
Ignore list: [0] mov:  0 index:  7 (0, 1) Ruta ciudad: [(14, 0)]
[0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.] 0.0 False
0 [-25, 0, 1, 2, 13, 14, 15, 16, 17, 26, 27, 28] True
0 1
Ignore list: [0] mov:  1 index:  8 (1, 1) Ruta ciudad: [(14, 0)]
[0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.] 0.0 False
1 [-25, 0, 1, 2, 13, 14, 15, 16, 17, 26, 27, 28] True
0 2
Ignore list: [0] mov:  2 index:  9 (2, 1) Ruta ciudad: [(14, 0)]
[0. 0. 0. 0. 1. 1.

2 6
Ignore list: [0] mov:  32 index:  8 (32, 1) Ruta ciudad: [(14, 0), (17, 3), (31, 1), (45, 1)]
[0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0.] 0.0 False
32 [6, 17, 18, 19, 20, 21, 30, 31, 32, 33, 34, 42, 43, 44, 45, 46, 47, 56, 57, 58, 59, 60, 69, 70, 71, 72, 73, 84] True
2 7
Ignore list: [0] mov:  33 index:  9 (33, 1) Ruta ciudad: [(14, 0), (17, 3), (31, 1), (45, 1)]
[0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0.] 1.0 True
33 [6, 17, 18, 19, 20, 21, 30, 31, 32, 33, 34, 42, 43, 44, 45, 46, 47, 56, 57, 58, 59, 60, 69, 70, 71, 72, 73, 84] True
Cost: 16, 12.2
True
Mov:  33
2 8
Ignore list: [0] mov:  34 index:  10 (34, 2) Ruta ciudad: [(14, 0), (17, 3), (31, 1), (45, 1)]
[0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0.] 1.0 True
34 [6, 17, 18, 19, 20, 21, 30, 31, 32, 33, 34, 42, 43, 44, 45, 46, 47, 56, 57, 58, 59, 60, 69, 70, 71, 72, 73, 84] True
Cost: 13, 12.4
False
3 3
Ignore list: [0] mov:  42 index:  11 (42, 3) Ruta ciudad: [(14, 0), (17, 3), (31, 1), (45, 1)]
[0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1.] 0.0 

Ignore list: [0] mov:  73 index:  26 (73, 2) Ruta ciudad: [(14, 0), (17, 3), (31, 1), (45, 1), (46, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0.] 0.0 False
73 [7, 18, 19, 20, 21, 22, 31, 32, 33, 34, 35, 43, 44, 45, 46, 47, 57, 58, 59, 60, 70, 71, 72, 85] False
5 9
Ignore list: [0] mov:  74 index:  27 (74, 3) Ruta ciudad: [(14, 0), (17, 3), (31, 1), (45, 1), (46, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0.] 1.0 True
74 [7, 18, 19, 20, 21, 22, 31, 32, 33, 34, 35, 43, 44, 45, 46, 47, 57, 58, 59, 60, 70, 71, 72, 85] False
6 7
Ignore list: [0] mov:  85 index:  28 (85, 3) Ruta ciudad: [(14, 0), (17, 3), (31, 1), (45, 1), (46, 1)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1.] 0.0 False
85 [7, 18, 19, 20, 21, 22, 31, 32, 33, 34, 35, 43, 44, 45, 46, 47, 57, 58, 59, 60, 70, 71, 72, 85] True
Candidate:  34
Ruta ciudad: [(14, 0), (17, 3), (31, 1), (45, 1), (46, 1)]
LOS:  [-5, 6, 7, 8, 19, 20, 21, 22, 31, 32, 33, 34, 35, 45, 46, 47, 48, 49, 58, 59, 61, 62]
8 2 34
Movs:  [-5, 6, 7, 8, 9, 10, 19, 20, 21, 2

Ignore list: [0] mov:  37 index:  27 (37, 3) Ruta ciudad: [(14, 0), (17, 3), (31, 1), (45, 1), (46, 1), (34, 1), (21, 1), (9, 1)]
[0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0.] 1.0 True
37 [-30, -19, -18, -17, -16, -15, -6, -5, -4, -3, -2, 6, 7, 8, 9, 10, 11, 12, 20, 21, 22, 23, 24, 33, 34, 36, 37] True
Cost: 12, 10.6
False
3 9
Ignore list: [0] mov:  48 index:  28 (48, 3) Ruta ciudad: [(14, 0), (17, 3), (31, 1), (45, 1), (46, 1), (34, 1), (21, 1), (9, 1)]
[0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1.] 0.0 False
48 [-30, -19, -18, -17, -16, -15, -6, -5, -4, -3, -2, 6, 7, 8, 9, 10, 11, 12, 20, 21, 22, 23, 24, 33, 34, 36, 37] False
Candidate:  24
Ruta ciudad: [(14, 0), (17, 3), (31, 1), (45, 1), (46, 1), (34, 1), (21, 1), (9, 1)]
LOS:  [-15, -4, -3, -2, 9, 10, 11, 12, 22, 23, 24, 25, 35, 36, 37, 38, 48, 49, 50, 63]
11 1 24
Movs:  [-15, -4, -3, -2, -1, 0, 9, 10, 11, 12, 13, 21, 22, 23, 24, 25, 26, 27, 35, 36, 37, 38, 39, 48, 49, 50, 51, 52, 63]
0 9
Ignore list: [0] mov:  9 index:  6 (9, 2) Ruta ciudad

Ruta ciudad: [(14, 0), (17, 3), (31, 1), (45, 1), (46, 1), (34, 1), (21, 1), (9, 1), (24, 2), (37, 1), (51, 1)]
LOS:  [24, 37, 38, 39, 49, 50, 51, 52, 62, 63, 64, 75, 76, 77, 78, 89, 90, 91, 102]
11 4 63
Movs:  [24, 35, 36, 37, 38, 39, 48, 49, 50, 51, 52, 60, 61, 62, 63, 64, 65, 66, 74, 75, 76, 77, 78, 87, 88, 89, 90, 91, 102]
1 11
Ignore list: [0] mov:  24 index:  0 (24, 3) Ruta ciudad: [(14, 0), (17, 3), (31, 1), (45, 1), (46, 1), (34, 1), (21, 1), (9, 1), (24, 2), (37, 1), (51, 1), (63, 1)]
[0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0.] 1.0 True
24 [24, 37, 38, 39, 49, 50, 51, 52, 62, 63, 64, 75, 76, 77, 78, 89, 90, 91, 102] True
2 9
Ignore list: [0] mov:  35 index:  1 (35, 3) Ruta ciudad: [(14, 0), (17, 3), (31, 1), (45, 1), (46, 1), (34, 1), (21, 1), (9, 1), (24, 2), (37, 1), (51, 1), (63, 1)]
[0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0.] 0.0 False
35 [24, 37, 38, 39, 49, 50, 51, 52, 62, 63, 64, 75, 76, 77, 78, 89, 90, 91, 102] False
2 10
Ignore list: [0] mov:  36 index:  2 (36, 2) Ruta ciud

0 7
Ignore list: [0] mov:  7 index:  8 (7, 1) Ruta ciudad: [(20, 0)]
[0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.] 0.0 False
7 [-19, -6, -5, -4, 6, 7, 8, 9, 17, 18, 19, 20, 21, 22, 31, 32, 33, 34, 35, 44, 45, 46, 47, 48, 59] True
0 8
Ignore list: [0] mov:  8 index:  9 (8, 1) Ruta ciudad: [(20, 0)]
[0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.] 0.0 False
8 [-19, -6, -5, -4, 6, 7, 8, 9, 17, 18, 19, 20, 21, 22, 31, 32, 33, 34, 35, 44, 45, 46, 47, 48, 59] True
0 9
Ignore list: [0] mov:  9 index:  10 (9, 2) Ruta ciudad: [(20, 0)]
[0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.] 1.0 True
9 [-19, -6, -5, -4, 6, 7, 8, 9, 17, 18, 19, 20, 21, 22, 31, 32, 33, 34, 35, 44, 45, 46, 47, 48, 59] True
Cost: 100, 13.4
True
Mov:  9
1 4
Ignore list: [0] mov:  17 index:  11 (17, 3) Ruta ciudad: [(20, 0)]
[0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0.] 1.0 True
17 [-19, -6, -5, -4, 6, 7, 8, 9, 17, 18, 19, 20, 21, 22, 31, 32, 33, 34, 35, 44, 45, 46, 47, 48, 59] True
Cost: 15, 18.6
False
1 5
Ignore list: [0] mov:  18 index:  12 (18, 2

Ignore list: [0] mov:  44 index:  12 (44, 2) Ruta ciudad: [(20, 0), (34, 1), (46, 1)]
[0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1.] 0.0 False
44 [7, 18, 19, 20, 21, 22, 31, 32, 33, 34, 35, 43, 44, 45, 46, 47, 57, 58, 59, 60, 70, 71, 72, 85] True
3 6
Ignore list: [0] mov:  45 index:  13 (45, 1) Ruta ciudad: [(20, 0), (34, 1), (46, 1)]
[0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1.] 1.0 True
45 [7, 18, 19, 20, 21, 22, 31, 32, 33, 34, 35, 43, 44, 45, 46, 47, 57, 58, 59, 60, 70, 71, 72, 85] True
Cost: 13, 12.2
False
3 7
Ignore list: [0] mov:  46 index:  14 (46, 0) Ruta ciudad: [(20, 0), (34, 1), (46, 1)]
[0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1.] 1.0 True
46 [7, 18, 19, 20, 21, 22, 31, 32, 33, 34, 35, 43, 44, 45, 46, 47, 57, 58, 59, 60, 70, 71, 72, 85] True
3 8
Ignore list: [0] mov:  47 index:  15 (47, 1) Ruta ciudad: [(20, 0), (34, 1), (46, 1)]
[0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1.] 0.0 False
47 [7, 18, 19, 20, 21, 22, 31, 32, 33, 34, 35, 43, 44, 45, 46, 47, 57, 58, 59, 60, 70, 71, 72, 85] True
3 9
I

87 [61, 73, 74, 75, 84, 85, 86, 87, 88, 89, 90, 98, 99, 100, 101, 102, 111, 112, 113, 114, 115] True
6 10
Ignore list: [0] mov:  88 index:  15 (88, 1) Ruta ciudad: [(20, 0), (34, 1), (46, 1), (72, 2), (87, 2)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1.] 1.0 True
88 [61, 73, 74, 75, 84, 85, 86, 87, 88, 89, 90, 98, 99, 100, 101, 102, 111, 112, 113, 114, 115] True
Cost: 8, 5.2
True
Mov:  88
6 11
Ignore list: [0] mov:  89 index:  16 (89, 2) Ruta ciudad: [(20, 0), (34, 1), (46, 1), (72, 2), (87, 2)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1.] 0.0 False
89 [61, 73, 74, 75, 84, 85, 86, 87, 88, 89, 90, 98, 99, 100, 101, 102, 111, 112, 113, 114, 115] True
6 12
Ignore list: [0] mov:  90 index:  17 (90, 3) Ruta ciudad: [(20, 0), (34, 1), (46, 1), (72, 2), (87, 2)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1.] 1.0 True
90 [61, 73, 74, 75, 84, 85, 86, 87, 88, 89, 90, 98, 99, 100, 101, 102, 111, 112, 113, 114, 115] True
Cost: 6, 5.6
False
7 7
Ignore list: [0] mov:  98 index:  18 (98, 2) Ruta ciudad: [(20, 0), 

2 9
Ignore list: [0] mov:  35 index:  21 (35, 1) Ruta ciudad: [(21, 0)]
[0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0.] 0.0 False
35 [-18, -7, -6, -5, -4, -3, 6, 7, 8, 9, 10, 18, 19, 20, 21, 22, 32, 33, 34, 35, 45, 46, 47] True
2 10
Ignore list: [0] mov:  36 index:  22 (36, 2) Ruta ciudad: [(21, 0)]
[0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0.] 0.0 False
36 [-18, -7, -6, -5, -4, -3, 6, 7, 8, 9, 10, 18, 19, 20, 21, 22, 32, 33, 34, 35, 45, 46, 47] False
3 6
Ignore list: [0] mov:  45 index:  23 (45, 3) Ruta ciudad: [(21, 0)]
[0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1.] 1.0 True
45 [-18, -7, -6, -5, -4, -3, 6, 7, 8, 9, 10, 18, 19, 20, 21, 22, 32, 33, 34, 35, 45, 46, 47] True
Cost: 12, 14.6
False
3 7
Ignore list: [0] mov:  46 index:  24 (46, 2) Ruta ciudad: [(21, 0)]
[0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1.] 1.0 True
46 [-18, -7, -6, -5, -4, -3, 6, 7, 8, 9, 10, 18, 19, 20, 21, 22, 32, 33, 34, 35, 45, 46, 47] True
Cost: 12, 12.4
False
3 8
Ignore list: [0] mov:  47 index:  25 (47, 2) Ruta ciudad: [(21, 0)]
[0

5 8
Ignore list: [0] mov:  73 index:  26 (73, 2) Ruta ciudad: [(21, 0), (34, 1), (46, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0.] 0.0 False
73 [7, 18, 19, 20, 21, 22, 31, 32, 33, 34, 35, 43, 44, 45, 46, 47, 57, 58, 59, 60, 70, 71, 72, 85] False
5 9
Ignore list: [0] mov:  74 index:  27 (74, 3) Ruta ciudad: [(21, 0), (34, 1), (46, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0.] 1.0 True
74 [7, 18, 19, 20, 21, 22, 31, 32, 33, 34, 35, 43, 44, 45, 46, 47, 57, 58, 59, 60, 70, 71, 72, 85] False
6 7
Ignore list: [0] mov:  85 index:  28 (85, 3) Ruta ciudad: [(21, 0), (34, 1), (46, 1)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1.] 0.0 False
85 [7, 18, 19, 20, 21, 22, 31, 32, 33, 34, 35, 43, 44, 45, 46, 47, 57, 58, 59, 60, 70, 71, 72, 85] True
Candidate:  72
Ruta ciudad: [(21, 0), (34, 1), (46, 1)]
LOS:  [33, 44, 45, 46, 57, 58, 59, 60, 70, 71, 72, 73, 83, 84, 85, 86, 87, 96, 97, 98, 99, 100, 111]
7 5 72
Movs:  [33, 44, 45, 46, 47, 48, 57, 58, 59, 60, 61, 69, 70, 71, 72, 73, 74, 75, 83, 84, 85, 86, 87, 

Ignore list: [0] mov:  88 index:  8 (88, 1) Ruta ciudad: [(21, 0), (34, 1), (46, 1), (72, 2), (87, 2), (101, 1)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1.] 1.0 True
88 [73, 74, 75, 76, 77, 86, 87, 88, 89, 90, 98, 99, 100, 101, 102, 103, 104, 113, 114, 115, 116, 127, 128, 129, 140] True
Cost: 8, 5.2
True
Mov:  88
6 11
Ignore list: [0] mov:  89 index:  9 (89, 1) Ruta ciudad: [(21, 0), (34, 1), (46, 1), (72, 2), (87, 2), (101, 1)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1.] 0.0 False
89 [73, 74, 75, 76, 77, 86, 87, 88, 89, 90, 98, 99, 100, 101, 102, 103, 104, 113, 114, 115, 116, 127, 128, 129, 140] True
6 12
Ignore list: [0] mov:  90 index:  10 (90, 2) Ruta ciudad: [(21, 0), (34, 1), (46, 1), (72, 2), (87, 2), (101, 1)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1.] 1.0 True
90 [73, 74, 75, 76, 77, 86, 87, 88, 89, 90, 98, 99, 100, 101, 102, 103, 104, 113, 114, 115, 116, 127, 128, 129, 140] True
Cost: 6, 4.4
False
7 7
Ignore list: [0] mov:  98 index:  11 (98, 3) Ruta ciudad: [(21, 0), (34, 1), (46, 1

[0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.] 1.0 True
9 [-5, 6, 7, 8, 19, 20, 21, 22, 31, 32, 33, 34, 35, 45, 46, 47, 48, 49, 58, 59, 61, 62] False
0 10
Ignore list: [0] mov:  10 index:  5 (10, 3) Ruta ciudad: [(46, 0), (34, 1)]
[0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.] 0.0 False
10 [-5, 6, 7, 8, 19, 20, 21, 22, 31, 32, 33, 34, 35, 45, 46, 47, 48, 49, 58, 59, 61, 62] False
1 6
Ignore list: [0] mov:  19 index:  6 (19, 2) Ruta ciudad: [(46, 0), (34, 1)]
[0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0.] 0.0 False
19 [-5, 6, 7, 8, 19, 20, 21, 22, 31, 32, 33, 34, 35, 45, 46, 47, 48, 49, 58, 59, 61, 62] True
1 7
Ignore list: [0] mov:  20 index:  7 (20, 1) Ruta ciudad: [(46, 0), (34, 1)]
[0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0.] 1.0 True
20 [-5, 6, 7, 8, 19, 20, 21, 22, 31, 32, 33, 34, 35, 45, 46, 47, 48, 49, 58, 59, 61, 62] True
Cost: 100, 13.2
True
Mov:  20
1 8
Ignore list: [0] mov:  21 index:  8 (21, 1) Ruta ciudad: [(46, 0), (34, 1)]
[0. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 1. 0.] 1.0 True
21 [-5, 6, 7, 8, 19,

Candidate:  24
Ruta ciudad: [(46, 0), (34, 1), (21, 1), (9, 1)]
LOS:  [-15, -4, -3, -2, 9, 10, 11, 12, 22, 23, 24, 25, 35, 36, 37, 38, 48, 49, 50, 63]
11 1 24
Movs:  [-15, -4, -3, -2, -1, 0, 9, 10, 11, 12, 13, 21, 22, 23, 24, 25, 26, 27, 35, 36, 37, 38, 39, 48, 49, 50, 51, 52, 63]
0 9
Ignore list: [0] mov:  9 index:  6 (9, 2) Ruta ciudad: [(46, 0), (34, 1), (21, 1), (9, 1), (24, 2)]
[0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.] 1.0 True
9 [-15, -4, -3, -2, 9, 10, 11, 12, 22, 23, 24, 25, 35, 36, 37, 38, 48, 49, 50, 63] True
0 10
Ignore list: [0] mov:  10 index:  7 (10, 1) Ruta ciudad: [(46, 0), (34, 1), (21, 1), (9, 1), (24, 2)]
[0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.] 0.0 False
10 [-15, -4, -3, -2, 9, 10, 11, 12, 22, 23, 24, 25, 35, 36, 37, 38, 48, 49, 50, 63] True
0 11
Ignore list: [0] mov:  11 index:  8 (11, 1) Ruta ciudad: [(46, 0), (34, 1), (21, 1), (9, 1), (24, 2)]
[0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0.] 1.0 True
11 [-15, -4, -3, -2, 9, 10, 11, 12, 22, 23, 24, 25, 35, 36, 37, 38, 48, 

[0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1.] 1.0 True
50 [24, 37, 38, 39, 49, 50, 51, 52, 62, 63, 64, 75, 76, 77, 78, 89, 90, 91, 102] True
Cost: 100, 7.2
True
Mov:  50
3 12
Ignore list: [0] mov:  51 index:  9 (51, 1) Ruta ciudad: [(46, 0), (34, 1), (21, 1), (9, 1), (24, 2), (37, 1), (51, 1), (63, 1)]
[0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 1.] 1.0 True
51 [24, 37, 38, 39, 49, 50, 51, 52, 62, 63, 64, 75, 76, 77, 78, 89, 90, 91, 102] True
4 8
Ignore list: [0] mov:  60 index:  11 (60, 3) Ruta ciudad: [(46, 0), (34, 1), (21, 1), (9, 1), (24, 2), (37, 1), (51, 1), (63, 1)]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.] 0.0 False
60 [24, 37, 38, 39, 49, 50, 51, 52, 62, 63, 64, 75, 76, 77, 78, 89, 90, 91, 102] False
4 9
Ignore list: [0] mov:  61 index:  12 (61, 2) Ruta ciudad: [(46, 0), (34, 1), (21, 1), (9, 1), (24, 2), (37, 1), (51, 1), (63, 1)]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.] 0.0 False
61 [24, 37, 38, 39, 49, 50, 51, 52, 62, 63, 64, 75, 76, 77, 78, 89, 90, 91, 102] False
4 10
Ignore list: [0]

Cost: 10, 6.2
True
Mov:  63
4 12
Ignore list: [0] mov:  64 index:  9 (64, 1) Ruta ciudad: [(76, 0)]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.] 0.0 False
64 [37, 50, 62, 63, 64, 75, 76, 77, 78, 87, 88, 89, 90, 91, 100, 101, 102, 103, 104, 115] True
5 8
Ignore list: [0] mov:  73 index:  11 (73, 3) Ruta ciudad: [(76, 0)]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0.] 0.0 False
73 [37, 50, 62, 63, 64, 75, 76, 77, 78, 87, 88, 89, 90, 91, 100, 101, 102, 103, 104, 115] False
5 9
Ignore list: [0] mov:  74 index:  12 (74, 2) Ruta ciudad: [(76, 0)]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0.] 1.0 True
74 [37, 50, 62, 63, 64, 75, 76, 77, 78, 87, 88, 89, 90, 91, 100, 101, 102, 103, 104, 115] False
5 10
Ignore list: [0] mov:  75 index:  13 (75, 1) Ruta ciudad: [(76, 0)]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0.] 0.0 False
75 [37, 50, 62, 63, 64, 75, 76, 77, 78, 87, 88, 89, 90, 91, 100, 101, 102, 103, 104, 115] True
5 11
Ignore list: [0] mov:  76 index:  14 (76, 0) Ruta ciudad: [(76, 0)]
[0. 0. 0. 0. 0. 0. 0. 1. 

Ignore list: [0] mov:  109 index:  11 (109, 3) Ruta ciudad: [(111, 0), (112, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1.] 0.0 False
109 [73, 84, 85, 86, 87, 88, 97, 98, 99, 100, 101, 110, 111, 112, 113, 123, 124, 125, 126, 127, 136, 137, 138, 139, 140, 151] False
8 6
Ignore list: [0] mov:  110 index:  12 (110, 2) Ruta ciudad: [(111, 0), (112, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1.] 0.0 False
110 [73, 84, 85, 86, 87, 88, 97, 98, 99, 100, 101, 110, 111, 112, 113, 123, 124, 125, 126, 127, 136, 137, 138, 139, 140, 151] True
8 7
Ignore list: [0] mov:  111 index:  13 (111, 1) Ruta ciudad: [(111, 0), (112, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1.] 1.0 True
111 [73, 84, 85, 86, 87, 88, 97, 98, 99, 100, 101, 110, 111, 112, 113, 123, 124, 125, 126, 127, 136, 137, 138, 139, 140, 151] True
8 8
Ignore list: [0] mov:  112 index:  14 (112, 0) Ruta ciudad: [(111, 0), (112, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1.] 1.0 True
112 [73, 84, 85, 86, 87, 88, 97, 98, 99, 100, 101, 110, 111, 112, 11

In [191]:
def getTownBitRate(routes, bit_rates):
    rates = []
    for town_route in routes:
        dists = [dist for (rute, dist) in town_route]
        rates.append(bit_rates[max(dists)-1])
        
    return rates 

In [193]:
rates = getTownBitRate(routes, bit_rates)
print(rates)

[1, 1, 1, 1, 1, 1]


In [212]:
def getNumFSOs(poblation):
    n_fso = np.sum(poblation)
    print(np.sum(poblation))
    return n_fso
        

In [213]:
n_fso = getNumFSOs(poblation)

27.0


In [214]:
def getFitness(n_fso, costo_fso, towns_rates, towns_demography = 500e3, alpha = 0.5):
    
    fitness = alpha * n_fso * costo_fso
    tmp = 0

    for rate in towns_rates:
        tmp +=  rate * towns_demography
        
    fitness += (1 - alpha) * tmp
    
    return fitness
    

In [217]:
fitness = getFitness(n_fso, costo_antenas, rates)
#print(fitness)

1350.0


In [ ]:
def mutation(poblation, inaccessible_areas, towns, prob = 0.2):

    for row in range(poblation.shape[0]):
        for col in range(poblation.shape[1]):
            if row*poblation.shape[1] + col not in inaccessible_areas and np.random.uniform(0, 1) >= (1 - prob) and row*poblation.shape[1] + col not in towns:
                if poblation[row][col] == 1:
                    poblation[row][col] = 0
                else:
                    poblation[row][col] = 1

    return poblation

In [ ]:
def crossOver(new_poblation, best_poblation, prob = 0.3):
    for row in range(poblation.shape[0]):
        for col in range(poblation.shape[1]):
            if new_poblation[row][col] != last_poblation[row][col] and np.random.uniform(0, 1) >= (1 - prob):
                if new_poblation[row][col] == 1:
                    poblation[row][col] = 0
                else:
                    poblation[row][col] = 1
    

In [ ]:
def simulation():
    max_iteraciones = 100
    contador = 0
    costo_antenas = 100
    bit_rates = [10, 1, 0.1]
    best_poblation = np.zeros((9,13))
    avalaible_areas = np.ones((9,13))
    
    inaccessible = np.array([0, 1, 2, 6, 12,
                13, 22, 25,
                26, 27, 28, 29 ,30, 35, 38,
                39, 40, 41, 42, 47, 49,
                52, 53, 54, 55, 56, 60, 61, 62, 64,
                65, 66, 67, 68, 69, 70, 73, 75,
                78, 79, 80, 81, 82, 83,
                91, 92, 93, 94, 95, 96, 97,
                104, 105, 106, 107, 108, 109, 110, 113])
    
    
    