In [84]:
'''
𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙 = 𝐺𝑒𝑛𝑃𝑜𝑏()//Generar poblaciones aleatorias
𝑚𝑎𝑥𝐼𝑡𝑒𝑟𝑎𝑐𝑖𝑜𝑛𝑒𝑠 = 100
𝑐𝑜𝑛𝑡𝑎𝑑𝑜𝑟 = 0
𝑓𝑖𝑡𝑛𝑒𝑠𝑠 = 𝑔𝑒𝑡𝐹𝑖𝑡𝑛𝑒𝑠𝑠(𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙)
𝑊ℎ𝑖𝑙𝑒(𝑐𝑜𝑛𝑡𝑎𝑑𝑜𝑟 < 𝑚𝑎𝑥𝐼𝑡𝑒𝑟𝑎𝑐𝑖𝑜𝑛𝑒𝑠){
𝑐𝑟𝑜𝑠𝑠 = 𝑐𝑟𝑜𝑠𝑠𝑜𝑣𝑒𝑟(𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙, 0. 7)
𝑚𝑢𝑡 = 𝑚𝑢𝑡𝑎𝑐𝑖ó𝑛(𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙, 0. 3)
𝑛𝑒𝑤𝑃𝑜𝑏 = 𝑐𝑟𝑜𝑠𝑠. 𝑎𝑝𝑝𝑒𝑛𝑑(𝑚𝑢𝑡)
𝑛𝑒𝑤𝐹𝑖𝑡𝑛𝑒𝑠𝑠 = 𝑔𝑒𝑡𝐹𝑖𝑡𝑛𝑒𝑠𝑠(𝑛𝑒𝑤𝑃𝑜𝑏)
𝑖𝑓(𝑛𝑒𝑤𝐹𝑖𝑡𝑛𝑒𝑠𝑠 > 𝑓𝑖𝑡𝑛𝑒𝑠𝑠)
𝑓𝑖𝑡𝑛𝑒𝑠𝑠 = 𝑛𝑒𝑤𝐹𝑖𝑡𝑛𝑒𝑠𝑠
𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙 = 𝑔𝑒𝑡𝑃𝑜𝑏(𝑛𝑒𝑤𝑃𝑜𝑏, 𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙)//devuelve 50% de los
mejores, 25% aleatorio y 25% de los mejores de la población
anterior
𝑐𝑜𝑛𝑡𝑎𝑑𝑜𝑟 ++
}
𝑠𝑜𝑙𝑢𝑐𝑖ó𝑛 = 𝑔𝑒𝑡𝑀𝑒𝑗𝑜𝑟𝐶𝑟𝑜𝑚𝑜𝑠𝑜𝑚𝑎(𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙)
𝑟𝑒𝑡𝑢𝑟𝑛 𝑠𝑜𝑙𝑢𝑐𝑖ón

Conjuntos:

P: pueblos p={1, 2, 3, 4, 5, 6}
D: distancias entre antenas d={2.5, 5, 10} [Km]
Row: filas en la grilla r={1,...,9}
Col: columnas en la final c={1,...,13}

Parámetros:

Td: Tasa de bits en enlace a distancia d
C: Costo de antena
Dp: Demografía ciudad p. (Cantidad de habitantes)

Variables:

EP_r,c: {1, si existe pueblo en (r,c); 0, e.o.c.}
AA_r,c: {1, si el area en (r,c) es accesible; 0, e.o.c.}
UA_r,c: {1, si hay una antena ubicada en (r,c); 0, e.o.c.}
Tp: tasa de bits en pueblo p.

FO:

alpha*(1/sum(UA_r,c * C)) + (1-alpha)Tp*Dp

'''
import numpy as np

![image](grilla.png)

In [190]:
max_iteraciones = 100
contador = 0
costo_antenas = 100
bit_rates = [10, 1, 0.1]
avalaible_areas = np.ones((9,13))
print(avalaible_areas,
avalaible_areas.shape)

inaccessible = np.array([0, 1, 2, 6, 12,
                13, 22, 25,
                26, 27, 28, 29 ,30, 35, 38,
               39, 40, 41, 42, 47, 49,
               52, 53, 54, 55, 56, 60, 61, 62, 64,
               65, 66, 67, 68, 69, 70, 73, 75,
               78, 79, 80, 81, 82, 83,
               91, 92, 93, 94, 95, 96, 97,
               104, 105, 106, 107, 108, 109, 110, 113])

for row in range(avalaible_areas.shape[0]):
    for col in range(avalaible_areas.shape[1]):
        if row*avalaible_areas.shape[1] + col in inaccessible:
            avalaible_areas[row][col] = 0
            
print(avalaible_areas)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] (9, 13)
[[0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1.]]


In [86]:
town_matrix = np.zeros((9, 13))

ISP = 116

town = np.array([
    14, 20, 21,
    46,
    76,
    111, ISP
])



for row in range(town_matrix.shape[0]):
    for col in range(town_matrix.shape[1]):
        if row*town_matrix.shape[1] + col in town:
            town_matrix[row][col] = 1
            

print(town_matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]


In [87]:
np.random.uniform(0, 1)

0.33144158233957943

In [88]:
def genPob(inaccessible_areas, towns, n=1):
    poblation_matrix = np.array([[]])
    for iter in range(n):
        antenna_matrix = np.zeros((9, 13))
        for row in range(antenna_matrix.shape[0]):
            for col in range(antenna_matrix.shape[1]):
                if ((row*antenna_matrix.shape[1] + col not in inaccessible_areas and np.random.uniform(0, 1) >= 0.5) or (row*antenna_matrix.shape[1] + col in towns)):
                    antenna_matrix[row][col] = 1
        #print(antenna_matrix)
        if poblation_matrix.size == 0:
            poblation_matrix = antenna_matrix
        else:
            poblation_matrix = np.append(poblation_matrix, antenna_matrix, axis=0)
    return poblation_matrix
    

In [128]:
poblation = genPob(inaccessible, town)
print(poblation)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.]]


In [174]:
def getMovVector(pos, cols):
    mov = [                                            pos - 3*cols,
                   pos - 2*cols - 2, pos - 2*cols - 1, pos - 2*cols, pos - 2*cols + 1, pos - 2*cols + 2,
                       pos - cols - 2, pos - cols - 1, pos - cols, pos - cols + 1, pos - cols + 2,
                               pos - 3, pos - 2, pos - 1, pos, pos + 1, pos + 2, pos + 3,
                       pos + cols - 2, pos + cols - 1, pos + cols, pos + cols + 1, pos + cols + 2,
                   pos + 2*cols - 2, pos + 2*cols - 1, pos + 2*cols, pos + 2*cols + 1, pos + 2*cols + 2,
                                                       pos + 3*cols]
    dist = [          3,
                3, 2, 2, 2, 3,
                2, 1, 1, 1, 2,
             3, 2, 1, 0, 1, 2, 3,
                2, 1, 1, 1, 2,
                3, 2, 2, 2, 3,
                      3]
    return mov, dist


def getShortRoute(poblation_matrix, towns):
    possible_route = False
    rows = poblation_matrix.shape[0]
    cols = poblation_matrix.shape[1]
    vision_sizes = [1, 2, 3]
    routes = []
    for town in towns:
        print(poblation_matrix)
        if town == ISP:
            continue
        town_route = [(town, 0)]
        curr_pos = town
        ignore = [0]
        while curr_pos != 116:
            movs, dist = getMovVector(curr_pos, cols)
            
            orientation_x = curr_pos % cols
            orientation_y = int(curr_pos/cols)
            
            isp_orientation_x = ISP % cols
            isp_orientation_y = int(ISP/cols)
            
            print(orientation_x, orientation_y, curr_pos)
            #break
            candidate = 0
            dist_pos = 0
            print(movs)
            cost = 100
            for i, mov in enumerate(movs):
                tmp_orientation_y = orientation_y
                tmp_orientation_x = mov % cols
                
                if mov < 0 or mov > 116:
                    continue
                    
                elif i == 0:
                    tmp_orientation_y = orientation_y - 3
                elif i >= 1 and i <= 5:
                    tmp_orientation_y = orientation_y - 2
                    if tmp_orientation_y != int(mov/cols):
                        continue
                elif i >= 6 and i <= 10:
                    tmp_orientation_y = orientation_y - 1
                    if tmp_orientation_y != int(mov/cols):
                        continue

                elif i >= 11 and i <= 17:
                    tmp_orientation_y = orientation_y
                    if tmp_orientation_y != int(mov/cols):
                        continue
                        
                elif i >= 18 and i <= 22:
                    tmp_orientation_y = orientation_y + 1
                    if tmp_orientation_y != int(mov/cols):
                        continue
                        
                elif i >= 23 and i <= 27:
                    tmp_orientation_y = orientation_y + 2
                    if tmp_orientation_y != int(mov/cols):
                        continue
                elif i == 28:
                    tmp_orientation_y = orientation_y + 3
                #print(poblation_matrix)
                print(tmp_orientation_y, tmp_orientation_x)
                print(f"Ignore list: {ignore}", mov, i, (mov,dist[i]), f"Ruta ciudad: {town_route}")
                print(poblation_matrix[tmp_orientation_y], poblation_matrix[tmp_orientation_y][tmp_orientation_x], poblation_matrix[tmp_orientation_y][tmp_orientation_x] == 1)
                
                if poblation_matrix[tmp_orientation_y][tmp_orientation_x] == 1 and mov not in ignore and mov not in [rute for (rute, dist) in town_route]:
                    dif_x = isp_orientation_x - tmp_orientation_x
                    dif_y = isp_orientation_y - tmp_orientation_y
                    print(f"Cost: {cost}, {dif_x + dif_y + dist[i]*1.2}")
                    print(cost > dif_x + dif_y + dist[i]*2)
                    if cost > dif_x + dif_y + dist[i]*2:
                        cost = dif_x + dif_y + dist[i]*2
                        dist_pos = i
                        print("Mov: ", mov)
                        candidate = mov
               
            print("Candidate: ", candidate)
            if candidate != 0:
                print(f"Ruta ciudad: {town_route}")
                town_route.append((candidate, dist[dist_pos]))
                curr_pos = candidate
            else:
                print(f"Ruta ciudad: {town_route}")
                if town_route[-1] != (town, 0):
                    print(town_route[-1])
                    ignore.append(town_route[-1][0])
                    town_route.pop()
                    curr_pos = town_route[-1][0]
                    
        
        print(town_route)
        routes.append(town_route)
        
    print(routes)
    
    return routes

In [182]:
routes = getShortRoute(poblation, town)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 1. 1. 0. 1. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.]]
1 1 14
[-25, -14, -13, -12, -11, -10, -1, 0, 1, 2, 3, 11, 12, 13, 14, 15, 16, 17, 25, 26, 27, 28, 29, 38, 39, 40, 41, 42, 53]
0 0
Ignore list: [0] 0 7 (0, 1) Ruta ciudad: [(14, 0)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] 0.0 False
0 1
Ignore list: [0] 1 8 (1, 1) Ruta ciudad: [(14, 0)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] 0.0 False
0 2
Ignore list: [0] 2 9 (2, 1) Ruta ciudad: [(14, 0)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] 0.0 False
0 3
Ignore list: [0] 3 10 (3, 2) Ruta ciudad: [(14, 0)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] 0.0 False
1 0
Ignore list: [0] 13 13 (13, 1) Ruta ciudad: [(14, 0)]
[0. 1. 0. 1.

Ignore list: [0] 57 19 (57, 1) Ruta ciudad: [(14, 0), (16, 2), (17, 1), (18, 1), (45, 2)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 False
4 6
Ignore list: [0] 58 20 (58, 1) Ruta ciudad: [(14, 0), (16, 2), (17, 1), (18, 1), (45, 2)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 False
4 7
Ignore list: [0] 59 21 (59, 1) Ruta ciudad: [(14, 0), (16, 2), (17, 1), (18, 1), (45, 2)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 False
4 8
Ignore list: [0] 60 22 (60, 2) Ruta ciudad: [(14, 0), (16, 2), (17, 1), (18, 1), (45, 2)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 False
5 4
Ignore list: [0] 69 23 (69, 3) Ruta ciudad: [(14, 0), (16, 2), (17, 1), (18, 1), (45, 2)]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1.] 0.0 False
5 5
Ignore list: [0] 70 24 (70, 2) Ruta ciudad: [(14, 0), (16, 2), (17, 1), (18, 1), (45, 2)]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1.] 0.0 False
5 6
Ignore list: [0] 71 25 (71, 2) Ruta ciudad: [(14, 0), (16, 2), (17, 1), (18, 1), (45, 2)]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1.]

Ignore list: [0] 110 23 (110, 3) Ruta ciudad: [(14, 0), (16, 2), (17, 1), (18, 1), (45, 2), (46, 1), (72, 2), (86, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.] 0.0 False
8 7
Ignore list: [0] 111 24 (111, 2) Ruta ciudad: [(14, 0), (16, 2), (17, 1), (18, 1), (45, 2), (46, 1), (72, 2), (86, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.] 1.0 True
Cost: 6, 7.4
False
8 8
Ignore list: [0] 112 25 (112, 2) Ruta ciudad: [(14, 0), (16, 2), (17, 1), (18, 1), (45, 2), (46, 1), (72, 2), (86, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.] 1.0 True
Cost: 6, 6.4
False
8 9
Ignore list: [0] 113 26 (113, 2) Ruta ciudad: [(14, 0), (16, 2), (17, 1), (18, 1), (45, 2), (46, 1), (72, 2), (86, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.] 0.0 False
8 10
Ignore list: [0] 114 27 (114, 3) Ruta ciudad: [(14, 0), (16, 2), (17, 1), (18, 1), (45, 2), (46, 1), (72, 2), (86, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.] 1.0 True
Cost: 6, 5.6
False
Candidate:  100
Ruta ciudad: [(14, 0), (16, 2), (17, 1), (18, 1), (45, 2), (46,

Ignore list: [0] 35 21 (35, 1) Ruta ciudad: [(20, 0), (21, 1)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.] 0.0 False
2 10
Ignore list: [0] 36 22 (36, 2) Ruta ciudad: [(20, 0), (21, 1)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.] 1.0 True
Cost: 13, 10.4
True
Mov:  36
3 6
Ignore list: [0] 45 23 (45, 3) Ruta ciudad: [(20, 0), (21, 1)]
[0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.] 1.0 True
Cost: 12, 14.6
False
3 7
Ignore list: [0] 46 24 (46, 2) Ruta ciudad: [(20, 0), (21, 1)]
[0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.] 1.0 True
Cost: 12, 12.4
False
3 8
Ignore list: [0] 47 25 (47, 2) Ruta ciudad: [(20, 0), (21, 1)]
[0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.] 0.0 False
3 9
Ignore list: [0] 48 26 (48, 2) Ruta ciudad: [(20, 0), (21, 1)]
[0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.] 0.0 False
3 10
Ignore list: [0] 49 27 (49, 3) Ruta ciudad: [(20, 0), (21, 1)]
[0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.] 0.0 False
4 8
Ignore list: [0] 60 28 (60, 3) Ruta ciudad: [(20, 0), (21, 1)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.] 0.0 False
3 10
Ignore list: [0] 49 27 (49, 3) Ruta ciudad: [(21, 0)]
[0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.] 0.0 False
4 8
Ignore list: [0] 60 28 (60, 3) Ruta ciudad: [(21, 0)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 False
Candidate:  36
Ruta ciudad: [(21, 0)]
10 2 36
[-3, 8, 9, 10, 11, 12, 21, 22, 23, 24, 25, 33, 34, 35, 36, 37, 38, 39, 47, 48, 49, 50, 51, 60, 61, 62, 63, 64, 75]
0 8
Ignore list: [0] 8 1 (8, 3) Ruta ciudad: [(21, 0), (36, 2)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] 0.0 False
0 9
Ignore list: [0] 9 2 (9, 2) Ruta ciudad: [(21, 0), (36, 2)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] 0.0 False
0 10
Ignore list: [0] 10 3 (10, 2) Ruta ciudad: [(21, 0), (36, 2)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] 0.0 False
0 11
Ignore list: [0] 11 4 (11, 2) Ruta ciudad: [(21, 0), (36, 2)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.] 1.0 True
Cost: 100, 11.4
True
Mov:  11
0 12
Ignore list: [0] 12 5 (12, 3) Ruta ciudad: [(21, 0), (36, 2)]
[0. 0. 

[0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.] 1.0 True
3 8
Ignore list: [0] 47 15 (47, 1) Ruta ciudad: [(46, 0)]
[0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.] 0.0 False
3 9
Ignore list: [0] 48 16 (48, 2) Ruta ciudad: [(46, 0)]
[0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.] 0.0 False
3 10
Ignore list: [0] 49 17 (49, 3) Ruta ciudad: [(46, 0)]
[0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.] 0.0 False
4 5
Ignore list: [0] 57 18 (57, 2) Ruta ciudad: [(46, 0)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 False
4 6
Ignore list: [0] 58 19 (58, 1) Ruta ciudad: [(46, 0)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 False
4 7
Ignore list: [0] 59 20 (59, 1) Ruta ciudad: [(46, 0)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 False
4 8
Ignore list: [0] 60 21 (60, 1) Ruta ciudad: [(46, 0)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 False
4 9
Ignore list: [0] 61 22 (61, 2) Ruta ciudad: [(46, 0)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 False
5 5
Ignore list: [0] 70 23 (70, 3) Ruta ciudad: [(46, 0)]
[0. 0. 0. 0. 0. 0. 

[0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.] 0.0 False
8 10
Ignore list: [0] 114 27 (114, 3) Ruta ciudad: [(46, 0), (72, 2), (86, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.] 1.0 True
Cost: 6, 5.6
False
Candidate:  100
Ruta ciudad: [(46, 0), (72, 2), (86, 1)]
9 7 100
[61, 72, 73, 74, 75, 76, 85, 86, 87, 88, 89, 97, 98, 99, 100, 101, 102, 103, 111, 112, 113, 114, 115, 124, 125, 126, 127, 128, 139]
4 9
Ignore list: [0] 61 0 (61, 3) Ruta ciudad: [(46, 0), (72, 2), (86, 1), (100, 1)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 0.0 False
5 7
Ignore list: [0] 72 1 (72, 3) Ruta ciudad: [(46, 0), (72, 2), (86, 1), (100, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1.] 1.0 True
5 8
Ignore list: [0] 73 2 (73, 2) Ruta ciudad: [(46, 0), (72, 2), (86, 1), (100, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1.] 0.0 False
5 9
Ignore list: [0] 74 3 (74, 2) Ruta ciudad: [(46, 0), (72, 2), (86, 1), (100, 1)]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1.] 1.0 True
Cost: 100, 8.4
True
Mov:  74
5 10
Ignore list: [0] 75 4 (75, 2

6 12
Ignore list: [0] 90 21 (90, 1) Ruta ciudad: [(76, 0)]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0.] 0.0 False
7 9
Ignore list: [0] 100 23 (100, 3) Ruta ciudad: [(76, 0)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] 1.0 True
Cost: 5, 7.6
False
7 10
Ignore list: [0] 101 24 (101, 2) Ruta ciudad: [(76, 0)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] 0.0 False
7 11
Ignore list: [0] 102 25 (102, 2) Ruta ciudad: [(76, 0)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] 0.0 False
7 12
Ignore list: [0] 103 26 (103, 2) Ruta ciudad: [(76, 0)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.] 0.0 False
8 11
Ignore list: [0] 115 28 (115, 3) Ruta ciudad: [(76, 0)]
[0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1.] 0.0 False
Candidate:  77
Ruta ciudad: [(76, 0)]
12 5 77
[38, 49, 50, 51, 52, 53, 62, 63, 64, 65, 66, 74, 75, 76, 77, 78, 79, 80, 88, 89, 90, 91, 92, 101, 102, 103, 104, 105, 116]
2 12
Ignore list: [0] 38 0 (38, 3) Ruta ciudad: [(76, 0), (77, 1)]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.] 0.0 False
3 10
Ignore list: [0] 49 1

In [191]:
def getTownBitRate(routes, bit_rates):
    rates = []
    for town_route in routes:
        dists = [dist for (rute, dist) in town_route]
        rates.append(bit_rates[max(dists)-1])
        
    return rates 

In [193]:
rates = getTownBitRate(routes, bit_rates)
print(rates)

[1, 1, 1, 1, 1, 1]


In [212]:
def getNumFSOs(poblation):
    n_fso = np.sum(poblation)
    print(np.sum(poblation))
    return n_fso
        

In [213]:
n_fso = getNumFSOs(poblation)

27.0


In [214]:
def getFitness(n_fso, costo_fso, towns_rates, towns_demography = 500e3, alpha = 0.5):
    
    fitness = alpha * n_fso * costo_fso
    tmp = 0

    for rate in towns_rates:
        tmp +=  rate * towns_demography
        
    fitness += (1 - alpha) * tmp
    
    return fitness
    

In [217]:
fitness = getFitness(n_fso, costo_antenas, rates)
#print(fitness)

1350.0


In [ ]:
def mutation(poblation, inaccessible_areas, towns, prob):

    for row in range(poblation.shape[0]):
        for col in range(poblation.shape[1]):
            if row*poblation.shape[1] + col not in inaccessible_areas and np.random.uniform(0, 1) >= (1 - prob) and row*poblation.shape[1] + col not in towns:
                if poblation[row][col] == 1:
                    poblation[row][col] = 0
                else:
                    poblation[row][col] = 1

    return poblation

In [ ]:
def crossOver(new_poblation, last_poblation, prob):
    for row in range(poblation.shape[0]):
        for col in range(poblation.shape[1]):
            if new_poblation[row][col] != last_poblation[row][col] and np.random.uniform(0, 1) >= (1 - prob):
                if new_poblation[row][col] == 1:
                    poblation[row][col] = 0
                else:
                    poblation[row][col] = 1
    