In [183]:
'''
𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙 = 𝐺𝑒𝑛𝑃𝑜𝑏()//Generar poblaciones aleatorias
𝑚𝑎𝑥𝐼𝑡𝑒𝑟𝑎𝑐𝑖𝑜𝑛𝑒𝑠 = 100
𝑐𝑜𝑛𝑡𝑎𝑑𝑜𝑟 = 0
𝑓𝑖𝑡𝑛𝑒𝑠𝑠 = 𝑔𝑒𝑡𝐹𝑖𝑡𝑛𝑒𝑠𝑠(𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙)
𝑊ℎ𝑖𝑙𝑒(𝑐𝑜𝑛𝑡𝑎𝑑𝑜𝑟 < 𝑚𝑎𝑥𝐼𝑡𝑒𝑟𝑎𝑐𝑖𝑜𝑛𝑒𝑠){
𝑐𝑟𝑜𝑠𝑠 = 𝑐𝑟𝑜𝑠𝑠𝑜𝑣𝑒𝑟(𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙, 0. 7)
𝑚𝑢𝑡 = 𝑚𝑢𝑡𝑎𝑐𝑖ó𝑛(𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙, 0. 3)
𝑛𝑒𝑤𝑃𝑜𝑏 = 𝑐𝑟𝑜𝑠𝑠. 𝑎𝑝𝑝𝑒𝑛𝑑(𝑚𝑢𝑡)
𝑛𝑒𝑤𝐹𝑖𝑡𝑛𝑒𝑠𝑠 = 𝑔𝑒𝑡𝐹𝑖𝑡𝑛𝑒𝑠𝑠(𝑛𝑒𝑤𝑃𝑜𝑏)
𝑖𝑓(𝑛𝑒𝑤𝐹𝑖𝑡𝑛𝑒𝑠𝑠 > 𝑓𝑖𝑡𝑛𝑒𝑠𝑠)
𝑓𝑖𝑡𝑛𝑒𝑠𝑠 = 𝑛𝑒𝑤𝐹𝑖𝑡𝑛𝑒𝑠𝑠
𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙 = 𝑔𝑒𝑡𝑃𝑜𝑏(𝑛𝑒𝑤𝑃𝑜𝑏, 𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙)//devuelve 50% de los
mejores, 25% aleatorio y 25% de los mejores de la población
anterior
𝑐𝑜𝑛𝑡𝑎𝑑𝑜𝑟 ++
}
𝑠𝑜𝑙𝑢𝑐𝑖ó𝑛 = 𝑔𝑒𝑡𝑀𝑒𝑗𝑜𝑟𝐶𝑟𝑜𝑚𝑜𝑠𝑜𝑚𝑎(𝑝𝑜𝑏𝐴𝑐𝑡𝑢𝑎𝑙)
𝑟𝑒𝑡𝑢𝑟𝑛 𝑠𝑜𝑙𝑢𝑐𝑖ón

Conjuntos:

P: pueblos p={1, 2, 3, 4, 5, 6}
D: distancias entre antenas d={2.5, 5, 10} [Km]
Row: filas en la grilla r={1,...,9}
Col: columnas en la final c={1,...,13}

Parámetros:

Td: Tasa de bits en enlace a distancia d
C: Costo de antena
Dp: Demografía ciudad p. (Cantidad de habitantes)

Variables:

EP_r,c: {1, si existe pueblo en (r,c); 0, e.o.c.}
AA_r,c: {1, si el area en (r,c) es accesible; 0, e.o.c.}
UA_r,c: {1, si hay una antena ubicada en (r,c); 0, e.o.c.}
Tp: tasa de bits en pueblo p.

FO:

alpha*(1/sum(UA_r,c * C)) + (1-alpha)Tp*Dp

'''
import numpy as np

![image](grilla.png)

In [184]:
max_iteraciones = 100
contador = 0
costo_antenas = 100
avalaible_areas = np.ones((9,13))
print(avalaible_areas,
avalaible_areas.shape)

inaccessible = np.array([0, 1, 2, 6, 12,
                13, 22, 25,
                26, 27, 28, 29 ,30, 35, 38,
               39, 40, 41, 42, 47, 49,
               52, 53, 54, 55, 56, 60, 61, 62, 64,
               65, 66, 67, 68, 69, 70, 73, 75,
               78, 79, 80, 81, 82, 83,
               91, 92, 93, 94, 95, 96, 97,
               104, 105, 106, 107, 108, 109, 110, 113])

for row in range(avalaible_areas.shape[0]):
    for col in range(avalaible_areas.shape[1]):
        if row*avalaible_areas.shape[1] + col in inaccessible:
            avalaible_areas[row][col] = 0
            
print(avalaible_areas)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] (9, 13)
[[0. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1.]]


In [185]:
town_matrix = np.zeros((9, 13))

town = np.array([
    14, 20, 21,
    46,
    76,
    111, 116
])

for row in range(town_matrix.shape[0]):
    for col in range(town_matrix.shape[1]):
        if row*town_matrix.shape[1] + col in town:
            town_matrix[row][col] = 1
            

print(town_matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]]


In [186]:
np.random.uniform(0, 1)

0.00981653974694452

In [187]:
def genPob(inaccessible_areas, towns, n=1):
    poblation_matrix = np.array([[]])
    for iter in range(n):
        antenna_matrix = np.zeros((9, 13))
        for row in range(antenna_matrix.shape[0]):
            for col in range(antenna_matrix.shape[1]):
                if ((row*antenna_matrix.shape[1] + col not in inaccessible_areas and np.random.uniform(0, 1) >= 0.5) or (row*antenna_matrix.shape[1] + col in towns)):
                    antenna_matrix[row][col] = 1
        #print(antenna_matrix)
        if poblation_matrix.size == 0:
            poblation_matrix = antenna_matrix
        else:
            poblation_matrix = np.append(poblation_matrix, antenna_matrix, axis=0)
    return poblation_matrix
    

In [188]:
poblation = genPob(inaccessible, town)
print(poblation)

[[0. 0. 0. 1. 1. 1. 0. 0. 1. 0. 1. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 1. 1.]]


In [193]:
def getMovVector(pos, cols):
    mov = [[pos - cols - 3, pos - cols - 2, pos - cols - 1, pos - cols, pos - cols + 1, pos - cols + 2, pos - cols + 3],
           [pos - 3, pos - 2, pos - 1, pos, pos + 1, pos + 2, pos + 3],
           [pos + cols - 3, pos + cols - 2, pos + cols - 1, pos + cols, pos + cols + 1, pos + cols + 2, pos + cols + 3]]
    return mov

def getShortRoute(poblation_matrix, towns):
    possible_route = False
    rows = poblation_matrix.shape[0]
    cols = poblation_matrix.shape[1]
    vision_sizes = [1, 2, 3]
    
    for town in towns:
        distance_allowed = 1
        while not possible_route:
            pos = town
            route = [pos]
            while route[-1] == 116:
                skip = False
                mov = getMovVector(pos, cols)
                for row in mov:
                    for step in range(distance_allowed*2 + 1):
                        print(int(len(row)/2), row[int(len(row)/2) - distance_allowed + step])
                        if row[int(len(row)/2) - distance_allowed + step] == 1:
                            route.append(int(step/2) - distance_allowed + step)
                            pos = int(step/2) - distance_allowed + step
                            skip = True
                            break
                    if skip == True:
                        print("hola")
                        break

                 
            
        

In [ ]:
getShortRoute(poblation, town)

In [191]:
def getFitness(poblation_matrix, costo_antenas, alpha = 0.5):
    n_antennas = np.sum(poblation_matrix)
    
    fitness = alpha * n_antennas * costo_antenas + (1 - alpha) * 
    
    return fitness
    

SyntaxError: invalid syntax (<ipython-input-191-9b2688bb935e>, line 4)

In [192]:
getFitness(poblation, costo_antenas)

36.0